timeout: 120 # How much time (in seconds) it takes to mark a player as afk.

movement: true # Whether or not to cancel when a player moves.
blocks: true # Wether or not to cancel when a player breaks or places a block.
chat: true # Whether or not to cancel when a player sends a chat message.
